# Introducción a NumPy

Recuerden que deben tener instalar el paquete NumPy a través de Miniconda y realizar la carga del mismo:

In [1]:
import numpy as np

## Tipos de Matrices en Python

Una de las principales ventajas de Python es la facilidad con que las variables son declaradas, sin tener que definir el tipo de variable.

En clases anteriores habíamos comentado que una variable en Python es un puntero a una celda en memoria que contiene un objeto. En términos más específicos, una variable en Python es un puntero a una estructura en C que contiene **al menos**:

1. Una variable que indica el tipo de objeto.
2. Una variable que contiene el tamaño del objeto.
3. El valor del objeto.

Una lista de Python por lo tanto, contiene un arreglo de objetos individuales que tienen las características anteriores. Esto permite que la estructura de lista sea muy flexible:

In [2]:
L = list(range(10))
print(L)
type(L[0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


int

In [3]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]


[bool, str, float, int]

Esta flexibilidad tiene un costo, más que todo en almacenamiento. Si todos los elementos de una lista tienen el mismo tipo de objeto, entonces NumPy ofrece una opción de almacenamiento con operadores eficientes sobre esas listas de *tipo estático*:

In [4]:
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

Estos arreglos deben contener valores del mismo tipo, de otra forma Python trata de subir la complejidad del tipo de objeto para que todos queden igual:

In [5]:
np.array([3.14, 4, 2, 3])


array([3.14, 4.  , 2.  , 3.  ])

Los arreglos de NumPy también puede ser multidimensionales:

In [6]:
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

También existen instrucciones para definir tipos específicos de arreglos en NumPy:

In [7]:
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3, 5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.random((3, 3))



array([[0.19180607, 0.14690741, 0.29794975],
       [0.78647363, 0.04484921, 0.44986817],
       [0.34100342, 0.89623163, 0.17699098]])

In [13]:
np.random.normal(0, 1, (3, 3))

array([[-0.24503515, -1.16065881,  0.19965936],
       [ 0.69706006, -0.24125061, -0.76661259],
       [-1.78933027,  0.62370154, -0.2301543 ]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

El tipo de valor que contiene el arreglo se puede modificar con el comando `dtype`, usando una cadena de texto, tipos predefinidos o propiedades del np:

In [15]:
np.zeros(10, dtype=bool)


array([False, False, False, False, False, False, False, False, False,
       False])

In [16]:
np.zeros(10, dtype=np.complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

## Manipulación básica de arreglos en NumPy
### Atributos

Primero definimos tres arreglos aleatorios con tres tamaños distintos e imprimimos algunos atributos:

In [17]:
np.random.seed(0)

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [18]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [19]:
print("dtype:", x3.dtype)


dtype: int64


In [20]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")


itemsize: 8 bytes
nbytes: 480 bytes


### Indexación

La indexación de arreglos en NumPy sigue las mismas reglas de la indexación en Python:

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
x1[0]

5

In [23]:
x1[4]

7

Para los arreglos multidimensionales se usa la coma como separador de dimensión:

In [24]:
x2[0, 0]
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x2[1, 2] = 16

In [26]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 16,  8],
       [ 1,  6,  7,  7]])

### Slicing (Submatrices)

Arreglos unidimensionales:

In [27]:
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[5:]

array([5, 6, 7, 8, 9])

In [30]:
x[::2]

array([0, 2, 4, 6, 8])

In [31]:
x[1::2]

array([1, 3, 5, 7, 9])

Arreglos multidimensionales:

In [32]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 16,  8],
       [ 1,  6,  7,  7]])

In [33]:
x2[:2, :3]

array([[ 3,  5,  2],
       [ 7,  6, 16]])

In [34]:
x2[:3, ::2]


array([[ 3,  2],
       [ 7, 16],
       [ 1,  7]])

In [35]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8, 16,  6,  7],
       [ 4,  2,  5,  3]])

También se puede acceder a filas o columnas completas:

In [36]:
print(x2[:, 0])
print(x2[0, :])
print(x2[0])
 

[3 7 1]
[3 5 2 4]
[3 5 2 4]


Un aspecto importante es que cualquier submatriz permite modificar la matriz original. Es decir, al definir submatrices no se crean copias de la matriz original.

In [37]:
print(x2)

[[ 3  5  2  4]
 [ 7  6 16  8]
 [ 1  6  7  7]]


In [38]:
x2_sub = x2[:2, :2]
print(x2_sub)


[[3 5]
 [7 6]]


In [39]:
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6 16  8]
 [ 1  6  7  7]]


Si queremos generar una submatriz que sea copia de la original, use `copy()`:

In [40]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)


[[99  5]
 [ 7  6]]


In [41]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6 16  8]
 [ 1  6  7  7]]


### Cambio de dimensiones en arreglos

Para cambiar las dimensiones de un arreglo se puede usar el comando `reshape` o bien los comandos `newaxis`:

In [42]:
x = np.array([1, 2, 3])
print(x.reshape((3, 1)))
print(x[np.newaxis, :])


[[1]
 [2]
 [3]]
[[1 2 3]]


### Concatenación y descomposición de arreglos

Para concatenar arreglos, usamos el comando `concatenate` o bien los comandos `vstack`y `hstack`:

In [43]:
grid = np.array([[1, 2, 3], [4, 5, 6]])


In [44]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [46]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
np.vstack([x, grid])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

Para descomponer arreglos usamos los comandos `split`, `hsplit` o bien `vsplit`:

In [47]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)


[1 2 3] [99 99] [3 2 1]


In [48]:
grid = np.arange(16).reshape((4, 4))
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [50]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Funciones Universales

La magia de Numpy es que puede bastante rápido si se usa adecuadamente. 

El secreto es usar todas sus funciones de forma vectorial en lugar de iterar en ciclos (for'ß o while's).

Este comportamiento es consistente en los lenguajes de programación modernos de alto nivel como Python. 

En Python, la forma de usar todo el poder de Numpy es a traves de las llamas `ufuncs`

### Operaciones unitarias

Todas las operaciones naturales que se pueden hacer con números unitarios, también se pueden hacer con objetos Numpy. Por ejemplo 

In [51]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5) # suma
print("x - 5 =", x - 5) # resta 
print("x * 2 =", x * 2) # multiplicacion
print("x / 2 =", x / 2) # división
print("x // 2 =", x // 2) # divisiónn hacia abajo
print("-x = ", -x) # negativos
print("x ** 2 = ", x ** 2) # potencias
print("x % 2 = ", x % 2) # módulo


x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


Estas operaciones están incluidas dentro de numpy como métodos internos.


In [52]:
print("x + 5 =", np.add(x,5)) # suma
print("x - 5 =",np.subtract(x,5)) # resta 
print("x * 2 =", np.multiply(x,5)) # multiplicacion

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [ 0  5 10 15]


Otras funciones cómunes son valor absoluto 

In [53]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [54]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [55]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [56]:
O funciones trigonométricas

SyntaxError: invalid syntax (<ipython-input-56-490a8ac853ae>, line 1)

In [57]:
theta = np.linspace(0, np.pi, 3)

print("theta       = ", theta)
print("sin(theta)  = ", np.sin(theta))
print("cos(theta)  = ", np.cos(theta))
print("tan(theta)  = ", np.tan(theta))


theta       =  [0.         1.57079633 3.14159265]
sin(theta)  =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)  =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)  =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Para la lista completa de `ufuncs` les recomiendo revisar la página https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

Algunas `ufuncs` pueden ser usadas de forma "iterada". Es decir, primero usar una función como suma y luego acumular el resultado o reducirlo a un solo valor. 

Para ver todas las posibilidades pueden ver la documentación https://numpy.org/doc/stable/reference/ufuncs.html#methods

Compare los siguientes resultados

In [58]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [59]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [60]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Otra `ufunc` bastante usada es outer que permite calcular la función deseada a todos los pares de valores de un vector. 

In [61]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

## Agregadores

Numpy puede hacer operaciones como sum, min, máx, etc sobre las dimensioes de un array.

Por ejemplo 


In [62]:
M = np.random.random((3, 4))
print(M)

[[0.65279032 0.63505887 0.99529957 0.58185033]
 [0.41436859 0.4746975  0.6235101  0.33800761]
 [0.67475232 0.31720174 0.77834548 0.94957105]]


In [63]:
M.sum()

7.435453494015987

In [64]:
np.sum(M)

7.435453494015987

In [65]:
sum(M)

array([1.74191123, 1.42695812, 2.39715515, 1.869429  ])

In [66]:
M.sum(axis=0)

array([1.74191123, 1.42695812, 2.39715515, 1.869429  ])

In [67]:
M.sum(axis=1)

array([2.86499909, 1.85058381, 2.7198706 ])

Una lista de funciones que tienen esta característica es 

np.sum  
np.prod  
np.mean  
np.std  
np.var  
np.min  
np.max  
np.argmin  
np.argmax  
np.median  
np.percentile
np.any  
np.all  


In [68]:
M = np.random.random((10,20))

In [69]:
np.percentile(M, 25,axis=0)

array([0.44997707, 0.47224822, 0.62686484, 0.24407913, 0.35041842,
       0.34756873, 0.2515787 , 0.132024  , 0.14462719, 0.2203927 ,
       0.58272196, 0.44675291, 0.14621455, 0.19213292, 0.33714571,
       0.40497464, 0.15091   , 0.24212321, 0.28662972, 0.55746903])

## Dispersión de matrices en NumPy

Recuerden que en NumPy uno puede aplicar operaciones elemento por elemento en arreglos de igual tamaño:

In [70]:
import numpy as np

In [71]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b


array([5, 6, 7])

La dispersión de matrices en NumPy permite aplicar operaciones binarias entre arreglos de distinto tamaño:

In [72]:
a+5

array([5, 6, 7])

En el caso de dimensiones más altas:

In [73]:
M = np.ones((3, 3))

In [74]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

en ambos casos el arreglo de menor dimensión es "dispersado" en el de mayor.

Otro caso:

In [75]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [76]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

En términos generales existen tres reglas en la dispersión de matrices en NumPy:
1. Si los dos arreglos tienen distinto número de dimensiones entonces el arreglo con menos dimensiones recibe dimensiones extra a la izquierda con 1s. 
2. Si el tamaño de alguna dimensión no es el mismo para dos arreglos, entonces se cambia el tamaño de dimensión cuyo tamaño es 1 al tamaño de la misma dimensión en el otro arreglo.
3. Si en alguna dimensión los tamaños de los dos arreglos difieren y no son igual a 1, entonces Python genera un error.

Primer Ejemplo:

In [77]:
M = np.ones((2, 3))
a = np.arange(3)
print(M.shape)
print(a.shape)

(2, 3)
(3,)


In [78]:
b = M + a
print(b)
print(b.shape)

[[1. 2. 3.]
 [1. 2. 3.]]
(2, 3)


Segundo ejemplo:

In [79]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a.shape)
print(b.shape)

(3, 1)
(3,)


In [80]:
print(a + b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


Tercer ejemplo:

In [81]:
M = np.ones((3, 2))
a = np.arange(3)
print(M.shape)
print(a.shape)

(3, 2)
(3,)


In [82]:
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

El error anterior se puede evitar al transponer el arreglo M:

In [83]:
Mt = M.transpose()
print(Mt.shape)

(2, 3)


In [84]:
Mt + a

array([[1., 2., 3.],
       [1., 2., 3.]])

Último ejemplo de dispersión: centrar un arreglo con datos

In [85]:
X = np.random.random((10, 3))
Xmean = X.mean(0)
Xmean


array([0.68393899, 0.53250073, 0.47447251])

In [86]:
X_centered = X - Xmean
X_centered

array([[ 0.30039044,  0.17099406, -0.29284131],
       [-0.17154553,  0.04794641,  0.31306964],
       [-0.07746353, -0.31409787, -0.0193037 ],
       [ 0.19493075, -0.04023248,  0.24108864],
       [-0.19777943,  0.17604742,  0.02366771],
       [ 0.16061109, -0.3381585 ,  0.2988535 ],
       [ 0.29031967,  0.32980905,  0.30595414],
       [ 0.30109329,  0.22106888, -0.47042441],
       [-0.41445956, -0.12200859, -0.04624868],
       [-0.38609717, -0.13136838, -0.35381552]])

In [87]:
X_centered.mean(0)

array([-1.11022302e-16, -4.44089210e-17, -6.66133815e-17])

## Arreglos booleanos y operadores de comparación

Los arreglos booleanos se pueden generar al comparar arreglos entrada por entrada, siguiendo las reglas de dispersión de matrices que vimos anteriormente:

In [88]:
x = np.array([1, 2, 3, 4, 5])
x < 3
 

array([ True,  True, False, False, False])

In [89]:
x >= 3
 

array([False, False,  True,  True,  True])

In [90]:
x != 3


array([ True,  True, False,  True,  True])

In [91]:
x == 3


array([False, False,  True, False, False])

También podemos hacer comparaciones más complejas entrada por entrada:

In [92]:
(2 * x) == (x ** 2)


array([False,  True, False, False, False])

Los arreglos booleanos permiten realizar operaciones sobre subconjuntos (o filtros) de arreglos:

In [93]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x


array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [94]:
np.count_nonzero(x < 6)

8

In [95]:
np.sum(x < 6)


8

También nos permite verificar condiciones sobre algunos o todos los elementos de un arreglo:

In [96]:
np.any(x > 8)


True

In [97]:
np.all(x == 6)


False

Los operadores booleanos también se pueden combinar con los operadores `&` (AND) y `|` (OR):

In [98]:
y = np.random.normal(size = 10)
y

array([-0.05508758,  0.28206989, -1.89431807,  0.83831078, -0.41631215,
        1.35692793, -1.19765944, -1.67704565,  1.01123333, -0.72812799])

In [99]:
np.sum(y > 0)

4

In [100]:
np.sum(~((y <= 0.5) | (y >= 1) ))

1

A partir de los arreglos booleanos que se obtienen al usar las operaciones anteriores, es posible crear filtros sobre los arreglos originales:

In [101]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [102]:
x < 5


array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [103]:
x[x < 5]


array([0, 3, 3, 3, 2, 4])

## Indexación elegante 

En los apartados anteriores se explicó como indexar arrays de forma simple (L[0]) o por secciones (L[:5]) o usando boleanos (L[L>0]). 


La Indexación elegante funciona igual que la Indexación simple, pero en lugar de pasar solo un escalar, vamos a usar otro array de índices. 

Por ejemplo 

In [104]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)


[51 92 14 71 60 20 82 86 74 74]


Queremos indexar los elementos 3, 7, 4. Entonces estás dos formas son totalmente equivalentes:

In [105]:
[x[3], x[7], x[4]]

[71, 86, 60]

In [106]:
ind = [3,7,4]
x[ind]

array([71, 86, 60])

También los índices de indexación definen la forma que tomará el resultado independientemente del array original.

In [107]:
X = np.arange(12).reshape((3, 4))
X


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
filas = np.array([0, 1, 2])
columnas = np.array([2, 1, 3])
X[filas, columnas]


array([ 2,  5, 11])

Usando las reglas de propagración que se vió en la sección pasada, podemos usar este estilo de indexación

In [109]:
filas[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [110]:
columnas 

array([2, 1, 3])

In [111]:
X[filas[:, np.newaxis], columnas]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

Incluso se puede combinar los diferentes estilos de Indexación con la Indexación elegante. 

In [112]:
 X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

Al igual que antes, podemos modificar arrays usando Indexación elegante, 

In [113]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
i = np.array([2, 1, 8, 4])

In [115]:
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


Hay que tener cuidado con la repetición de indices ya que puede pasar efectos nos deseados

In [116]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)


[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [117]:
x[0] = 4
print(x)

[4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [118]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [119]:
x[0] = 6
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ojo, este ejemplo 

In [120]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

Esperaríamos que x[3] sea 2 y x[4] es 3. La indexación lo que hizo fue x[i] = x[i] + 1

In [121]:
x = np.zeros(10)
x[i]

array([0., 0., 0., 0., 0., 0.])

In [122]:
x[i] = x[i] + 1
print(x)

[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]


In [123]:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)


[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


## Ordenamiento de arrays

Numpy es particularmente eficiente para ordenar arrays

In [124]:
# No modifica x
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [125]:
# Modifica x
x.sort()
print(x)

[1 2 3 4 5]


In [126]:
# argsort devuelve los indices
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)


[1 0 3 2 4]


In [127]:
x[i]

array([1, 2, 3, 4, 5])

También se pueden hacer ordenamientos sobre filas y columnas. 
**OJO: Este forma de ordenar destruye el orden de las matrices. Para ordenamiento de datos veremos que pandas es más vérsatil**

In [128]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)


[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [129]:
# Ordena las columnas 
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [130]:
# Ordena las filas
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

A veces solo queremos ordenar parcialmente un array


In [131]:
x = np.array([7, 2, 1, 3, 6, 5, 4])
np.partition(x, 3)

array([2, 3, 1, 4, 6, 5, 7])

## Datos structurados con Numpy

Pandas es una extension de Numpy donde en lugar de lidiar con valores numéricos, se trabajara con diccionarios. 

Sin embargo, todas las capacidad de indexación, asignación y propagación de Numpy estarán disponibles en Pandas. 

Solo como un ejemplo, observemos como se puede construir un `DataFrame` usando herramientas básicas de Numpy. En la próxima sección veremos los métodos de alto nivel para hacer esto más fácil.

In [132]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [133]:
 # Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})
print(data.dtype)


[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [134]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [135]:
type(data)

numpy.ndarray

Con esta construcción podemos indexar las columnas y filas de este array.

In [136]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [137]:
data[0]

('Alice', 25, 55.)